// Brand-matched carousel slide generation. Owner wants gpt-image-2 AND an exact match to the
// existing @recallengine template, so each slide is generated by the image-EDIT endpoint using a
// real brand slide as the style reference (assets/brand/cover.jpg + content.jpg). The reference
// carries the exact logomark, grid, colours and layout; the prompt swaps in the new text.
//
// Content slides render the point as a SPACED bullet list (not a paragraph) plus ONE small,
// clean cyan line icon, so there is a visual to anchor each point without clutter.

import sharp from "sharp";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { generateSlideImageRef } from "./openai.js";
import { config } from "./config.js";
import type { Post, SlidePoint } from "./types.js";

const BRAND_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "assets", "brand");
const COVER_REF = join(BRAND_DIR, "cover.jpg");
const CONTENT_REF = join(BRAND_DIR, "content.jpg");

const BRAND =
  "This is the Recall Engine brand template. Keep EXACTLY from the reference image: the deep navy " +
  "background with the faint grid, the cyan 'R' recall logomark together with the 'Recall Engine' " +
  "wordmark, the bright cyan accent colour, the heavy white sans-serif typography, and the clean premium " +
  "medical-tech layout. Replace ALL existing words with ONLY the new text given below, spelled exactly and " +
  "correctly, with no leftover text from the reference. No anatomical drawings, no photographs, no watermark.";

/** Bullet lines for a point: explicit bullets, else the paragraph body split into sentences. */
function pointLines(p: SlidePoint): string[] {
  if (p.bullets && p.bullets.length) return p.bullets.map((b) => b.trim()).filter(Boolean);
  return (p.body ?? "")
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function hookPrompt(post: Post): string {
  return (
    `${BRAND} Make a CENTERED cover slide like the reference. Keep the Recall Engine logomark near the top ` +
    `centre. A small cyan eyebrow label above the headline: "${post.subject.toUpperCase()}". Large centered ` +
    `headline: "${post.title}", with the 1-2 most important words in cyan and the rest white, then a short ` +
    `cyan underline. A muted-grey subline below: "${post.hook}".`
  );
}

function pointPrompt(post: Post, idx: number): string {
  const p = post.points[idx];
  const n = idx + 1;
  const lines = pointLines(p);
  const list = lines.map((l) => `• ${l}`).join("   ");
  const icon = p.icon ?? p.heading;
  return (
    `${BRAND} Make a LEFT-ALIGNED content slide like the reference. Keep the top-left Recall Engine logomark ` +
    `and the thin hairline, with a cyan-outlined chip in the TOP-RIGHT reading "p. 0${n}". Big left-aligned ` +
    `headline: "${p.heading}", with the key word in cyan and the rest white, then a short cyan underline. ` +
    `Below, render these as a VERTICAL bulleted list of ${lines.length} separate short lines, each led by a ` +
    `small cyan dot, with clear vertical SPACING between the lines (NOT a paragraph): ${list}. ` +
    `Place ONE small, simple, clean cyan line icon representing "${icon}" tastefully in the lower-right, ` +
    `minimal and not cluttering. Keep the navy grid background.`
  );
}

function ctaPrompt(post: Post): string {
  return (
    `${BRAND} Make a CENTERED closing slide. Keep the Recall Engine logomark near the top centre. Large ` +
    `centered headline: "${post.cta}", key words in cyan. A short amber underline beneath it. A cyan-outlined ` +
    `pill button reading "FOLLOW ${config.handle}". A small muted-grey footer line: "Save this post for revision".`
  );
}

/** Ordered prompt list (hook, points..., CTA). Exported for the smoke test. */
export function slidePrompts(post: Post): string[] {
  return [hookPrompt(post), ...post.points.map((_, i) => pointPrompt(post, i)), ctaPrompt(post)];
}

/** Generate all carousel slides for a post as processed square JPEG buffers, in order. */
export async function generateSlides(post: Post): Promise<Buffer[]> {
  const cover = await sharp(readFileSync(COVER_REF)).png().toBuffer();
  const content = await sharp(readFileSync(CONTENT_REF)).png().toBuffer();

  const jobs: Array<{ prompt: string; ref: Buffer }> = [
    { prompt: hookPrompt(post), ref: cover },
    ...post.points.map((_, i) => ({ prompt: pointPrompt(post, i), ref: content })),
    { prompt: ctaPrompt(post), ref: cover },
  ];

  // Render sequentially to respect the gpt-image-2 input-images/min rate limit (concurrency 429s).
  const out: Buffer[] = [];
  for (const job of jobs) {
    out.push(await toSquareJpeg(await generateSlideImageRef(job.prompt, job.ref)));
  }
  return out;
}

/** Normalize a generated image to a config.slideSize square JPEG. */
function toSquareJpeg(buf: Buffer): Promise<Buffer> {
  return sharp(buf)
    .resize(config.slideSize, config.slideSize, { fit: "cover", position: "centre" })
    .jpeg({ quality: 90, chromaSubsampling: "4:4:4" })
    .toBuffer();
}
